### ISSUE TITLE
ReplicaSet errors repeatedly

### ISSUE THREAD

**Issue by mohanrajatnetapp** [mongodb/mongodb-enterprise-kubernetes#103]
```json
{"logType":"automation-agent-verbose","contents":"[2020/06/03 01:53:26.135] [.error] [cm/mongoclientservice/mongoclientservice.go:withClientForHelper:403] <hardwareMetricsCollector> [01:53:26.135] Error checking out client (0x0) for connParam=opslog-backup-0.opslog-backup-svc.bva-db-opslog-stg.svc.cluster.local:27017 (local=false) connectMode=SingleConnect : [01:53:26.135] Error dialing to connParams=opslog-backup-0.opslog-backup-svc.bva-db-opslog-stg.svc.cluster.local:27017 (local=false): tried 1 identities, but none of them worked.  They were ()"}
```
Operator version 1.5.3
Openshift 3.11
```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: opslog-backup
  namespace: bva-db-opslog-stg

spec:
  connectivity:
    replicaSetHorizons:
    - horizon-dns-1: opslog-backup-0.prd02d.xxx.xxx.com:27017
    - horizon-dns-1: opslog-backup-1.prd02d.xxx.xxx.com:27017
    - horizon-dns-1: opslog-backup-2.prd02d.xxx.xxx.com:27017
  credentials: opsmanager-access
  members: 3
  opsManager:
    configMapRef:
      name: opsmanager-project
  persistent: true
  podSpec:
    cpu: 2000m
    cpuRequests: 500m
    memory: 4G
    memoryRequest: 2G
    memoryRequests: 1G
    persistence:
      single:
        storage: 500G
  security:
    authentication:
      enabled: true
      modes:
      - SCRAM
    tls:
      enabled: true
  type: ReplicaSet
  version: 3.6.18-ent
status:
  lastTransition: "2020-06-03T01:56:06Z"
  message: StatefulSet not ready
  phase: Pending
  resourcesNotReady:
  - kind: StatefulSet
    message: 'Not all the Pods are ready (total: 3, updated: 3, ready: 0)'
    name: opslog-backup
  type: ""
  version: ""
```
