### ISSUE TITLE
Error : no kind "MongoDB" is registered for version "mongodb.com/v1"

### ISSUE THREAD

**Issue by nithinkanil** [mongodb/mongodb-enterprise-kubernetes#105]
Deployed the replication with the following configuration
```
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  members: 3
  version: 4.2.1-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials

  persistent: false 
```
After deployment, I am getting the below-mentioned error

`error: no kind "MongoDB" is registered for version "mongodb.com/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

I am able to find the kind and version after executing kubectl explain mdb
```
KIND:     MongoDB
VERSION:  mongodb.com/v1

DESCRIPTION:
     <empty>

```

**Comment by antonlisovenko** [comment]
hi @nithinkanil 

thanks for reporting this.

Have you installed the necessary CRDs?
```
kubectl get crds
```

If you have all 3 CRDs - could you please show the Operator log? My assumption that this error happens right after the Operator has started trying to create the first `MongoDB` object - is this correct?

**Comment by nithinkanil** [comment]
@antonlisovenko antonlisovenkoPlease find below the output for kubectl get crds
```
backendconfigs.cloud.google.com                2020-06-08T15:41:33Z
capacityrequests.internal.autoscaling.k8s.io   2020-06-08T15:41:18Z
managedcertificates.networking.gke.io          2020-06-08T15:41:20Z
mongodb.mongodb.com                            2020-06-08T15:46:44Z
mongodbusers.mongodb.com                       2020-06-08T15:46:45Z
opsmanagers.mongodb.com                        2020-06-08T15:46:46Z
scalingpolicies.scalingpolicy.kope.io          2020-06-08T15:41:19Z
storagestates.migration.k8s.io                 2020-06-08T15:41:21Z
storageversionmigrations.migration.k8s.io      2020-06-08T15:41:21Z
updateinfos.nodemanagement.gke.io              2020-06-08T15:41:21Z
```
Please find below the operator log

`error: no kind "MongoDB" is registered for version "mongodb.com/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

**Comment by antonlisovenko** [comment]
@nithinkanil 
What is the Operator version?
How did you install the Operator? (have you used special options, modified the installation scripts)
What is the environment you are running in? Based on the other CRDs this seems to be GKE? Is it a private cluster?
Do you have any special security restrictions in your cluster?
Can you please show the output from `kubectl get crd mongodb.mongodb.com -o yaml`?

> Please find below the operator log

One line from the log doesn't give much information, can you please show the full log?

In general: it's hard to guess the reason as under normal conditions the Operator shouldn't have any problems getting access to the CRDs - this is ensured by the role `mongodb-enterprise-operator`:
```
- apiGroups:
  - mongodb.com
  resources:
  - mongodb
  - mongodb/finalizers
  - mongodbusers
  - opsmanagers
  - opsmanagers/finalizers
  - mongodb/status
  - mongodbusers/status
  - opsmanagers/status
  verbs:
  - "*"
```

If the answers to the previous questions don't give much information I'd recommend to try some other K8s cluster (minikube, kind, other public K8s cluster) and check if the Operator works there.
