### ISSUE TITLE
TLS related error message "Entries must contain a certificate and a private key" but the secret entry does contain both

### ISSUE THREAD

**Issue by croeck** [mongodb/mongodb-enterprise-kubernetes#110]
Using operator version 1.5.4

I am trying to setup TLS for my ReplicaSet, but fail with the following error message:

```
The Secret *****-cert containing certificates is not valid. Entries must contain a certificate and a private key.	{"ReplicaSet": "mongodb/*****"}
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/workflow.failedStatus.Log
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/workflow/failed.go:67
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatus
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:227
github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbReplicaSet).Reconcile
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbreplicaset_controller.go:107
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```

My deployment is:

```
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: *****
  namespace: mongodb
spec:
  members: 1
  version: 4.2.8
  type: ReplicaSet
  podSpec:
    memory: 4096M
    persistence:
      single:
        storage: 16G
        storageClass: longhorn
  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: *****-opm-credentials-secret
  security:
    tls:
      enabled: true
      ca: *****-tls-ca
    authentication:
      enabled: true
      ignoreUnknownUsers: true
      modes:
        - SCRAM
```

The mentioned secret looks like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: *****-cert
  namespace: mongodb
stringData:
  *****-0-pem: |-
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----
```

and I do also have the configmap for the ca data:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: *****-tls-ca
  namespace: mongodb
data:
  ca-pem: |-
    ...
```

I also tested the pem file (extracted from kubernetes again) with openssl:
`openssl verify -CAfile *****-0.pem ca.pem` which returned `OK`

What am I missing, how can we debug this further to get to the root cause? Thanks!

**Comment by croeck** [comment]
Ok, after lots of debugging and comparing the instructions on https://docs.mongodb.com/kubernetes-operator/v1.5/tutorial/secure-tls/ to some other pages, I figured there are some requirements to the TLS certificate listed here: https://docs.mongodb.com/kubernetes-operator/master/tutorial/secure-om-with-tls/

**Solution:**

- The DNS name of the certificate must follow this pattern:
`<metadata.name>-<index>.<metadata.name>-svc.<namespace>.svc.cluster.local`
- The usage must specify server and client auth

```
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
spec:
  ...
  usages:
    - server auth
    - client auth
  dnsNames:
    - *****-0.*****-svc.mongodb.svc.cluster.local
```

In my opinion **this is a bug** since the operator outputs a wrong error messages. The certificate and its private key are both there, they are just **not satisfying the expectations** and this must be reflected in the **error message** as well. I will leave the ticket open until you had a look and can categorise it.
