### ISSUE TITLE
OpenShift - "edit" role doesn't have "list" or "get" verb privileges

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#123]
Hi,
Using OpenShift 3.11 currently.
When applying the yaml (cluster-wide configuration) the operator works pretty well, but the roles "edit-mongodb*.mongodb.com-v1" don't seem to have "get" or "list" permissions. It affects RBAC actions on namespaces by namespace admins that are getting those "edit" privileges.
Can't find the roles definitions in the YAML - Maybe those are in the operator itself?

**Comment by rodrigovalin** [comment]
Hello,

The operator roles for the `mongodb.com` resource are defined as (The `*` verb is defined so the `list` and `get` are defined as well):

```yaml
- apiGroups:
  - mongodb.com
  resources:
  - mongodb
  - mongodb/finalizers
  - mongodbusers
  - opsmanagers
  - opsmanagers/finalizers
  verbs:
  - "*"
```

With regards to:

> It affects RBAC actions on namespaces by namespace admins that are getting those "edit" privileges

Can you clarify this point? I'm not sure I understand.

Thanks
