### ISSUE TITLE
Standalone mode permissions prevents change of directoryPerDB

### ISSUE THREAD

**Issue by miguel-callejas-coderoad-com** [mongodb/mongodb-enterprise-kubernetes#126]
When deploying a mongodb-standalone mode with the following example YAML:

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb-standalone
spec:
  #Mandatory Fields
  version: 4.2.1-ent
  type: Standalone
  opsManager:
    configMapRef:
      name: mongodb-configmap
  credentials: opsmanager-credentials
  persistent: true
  #Optional Fields
  logLevel: INFO
  #featureCompatibilityVersion:
  exposedExternally: true
  podSpec:
    cpu: "2"
    cpuRequests: 512m
    memory: "4Gi"
    memoryRequests: "2Gi"
    persistence:
      single:
        storage: 30Gi
        storageClass: premium
```

Executing a change via OpsManager to add the following parameters doesn't work. 
```
storage.directoryPerDB=true
storage.wiredTiger.engineConfig.directoryForIndexes=true
```

The user facing issue is a `No plan could be found!` but digging I found that for standalone servers, mongodb uses mongodump and mongorestore to change directory properties. And while executing the backup, the container doesn't have permissions to write on the mounted folder:

```
Failed to apply action. Result = <nil> : <mongodb-standalone> [23:11:55.531] Error backing up db files : <mongodb-standalone> [23:11:55.531] Error creating backup dbpath for /data in / : mkdir /data.backup.978134126: permission denied
```

Logged in into the container, and there are no permissions to write in any folder with the user. 
This does not happen in a replicaSet cluster since the change is being done in cascade without the need of mongodump/mongorestore.

```
Google Kubernetes Engine
System Info:
 Kernel Version:             4.14.138+
 OS Image:                   Container-Optimized OS from Google
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.7
 Kubelet Version:            v1.13.12-gke.25
 Kube-Proxy Version:         v1.13.12-gke.25
```
