### ISSUE TITLE
Invalid value: "string": spec.security.tls.secretRef in body must be of type object: "string"

### ISSUE THREAD

**Issue by gbarrett1988** [mongodb/mongodb-enterprise-kubernetes#127]
Hey mongo guys,

Trying to deploy ops-manager with TLS & Custom CA (APPDB TLS not necessary for me) within my company's corporate network.

I followed the documentation and also created the necessary ConfigMap containing the Custom CA root certificate. But when I try to deploy ops-manager I immediately get the following:

```
$ kubectl apply -f ./ops-manager.yaml
Invalid value: "string": spec.security.tls.secretRef in body must be of type object: "string"
```

Is this just an issue with my kubernetes setup or with ops-manager?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Following documentation here:
https://docs.mongodb.com/kubernetes-operator/master/tutorial/deploy-om-container/#deploy-om-container

Using commit July 31 2020: 251efd041761e33e985015bd10dfbd01d1018286

ops-manager.yaml
```
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  # the number of Ops Manager instances to run. Set to value bigger
  # than 1 to get high availability and upgrades without downtime
  replicas: 3

  # the version of Ops Manager distro to use
  version: 4.4.0

  # optional. Specify the custom cluster domain of the Kubernetes cluster if it's different from the default one ('cluster.local').
  # This affects the urls generated by the Operator.
  # This field is also used for Application Database url
  clusterDomain: ops-manager.k8s.cluster.corp.domain

  # the name of the secret containing admin user credentials.
  # Either remove the secret or change the password using Ops Manager UI after the Ops Manager
  # resource is created!
  adminCredentials: ops-manager-admin-secret

  # optional. The Ops Manager configuration. All the values must be of type string
  configuration:
    automation.versions.source: local

  security:
    # enables TLS for Ops Manager allowing it to serve traffic over HTTPS
    tls:
      # secret containing the TLS certificate signed by known or custom CA. The secret must have a key "server.pem"
      # and value of .pem file containing private key and TLS certificate
      secretRef: om-http-cert

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    # optional. Configures the version of MongoDB used as an application database.
    # The bundled MongoDB binary will be used if omitted and no download from the Internet will happen
    version: 4.2.8-ent
    persistent: true
```
