### ISSUE TITLE
Cannot specify the persistent volume claim in the ops manager yaml file

### ISSUE THREAD

**Issue by tareksalem** [mongodb/mongodb-enterprise-kubernetes#140]
This is my ops manager yaml configuration file
```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  replicas: 3
  version: 4.4.1
  adminCredentials: ops-manager-admin-secret
  configuration:
    mms.testUtil.enabled: "true"
  backup:
    enabled: true
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongodb-backup-daemon
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
            key1: value1
        spec:
          volumes:
            - name: mongo-persistent-storage
              persistentVolumeClaim:
              claimName: mongo-pvc
          containers:
            - name: mongodb-ops-manager
              volumeMounts:
                - mountPath: /data/db
                  name: mongo-persistent-storage
          tolerations:
            - key: "key"
              operator: "Exists"
              effect: "NoSchedule"
  externalConnectivity:
    type: NodePort
  applicationDatabase:
    members: 3
    podSpec:
        persistence:
          single:
            storage: 5G

        podTemplate:
          spec:
            volumes:
            - name: mongo-persistent-storage
              persistentVolumeClaim:
              claimName: mongo-pvc
            containers:
              - name: appdb-sidecar
                image: busybox
                command: ["sleep"]
                args: [ "infinity" ]
                resources:
                  limits:
                    cpu: "1"
                  requests:
                    cpu: 500m
              - name: mongodb-ops-manager
                volumeMounts:
                  - mountPath: /data/db
                    name: mongo-persistent-storage
```
I try to specify the name of the persistent volume and volume mounts but don't take any effect on the created pods and the pod selects the persistent volume claim randomly

When I apply the ops manager YAML file, the related pods cannot start and get this message inside them

  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "ops-manager-db-1": pod has unbound immediate PersistentVolumeClaims

**Comment by tareksalem** [comment]
can anyone help me, please !!!

**Comment by antonlisovenko** [comment]
hi @tareksalem 

Could you describe in more details what you are trying to achieve? Do you want to use the custom PVC for appdb or OM or both?
Can you show the code for the `mongo-pvc` PVC?
In the example given I see some inconsistencies:
* `mongodb-ops-manager` container is mentioned for both `spec.applicationDatabase` and `spec`
* the same mount configuration is used for both `spec` and `spec.applicationDatabase`

**Comment by tareksalem** [comment]
HI @antonlisovenko 
Thanks for your reply,

Actually what I need is define the persistent volumes for both appdb and OM, because when I create the om without defining the PVC the created containers takes a random persistent volume claim

Here is my PVC definition

```
piVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-ops-manager-db-1
spec:
  storageClassName: mongodb-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

```

The PVC is created successfully and it's based on CEPH block storage, the Idea here I have tried different things to define the volumes and volume mounts but not working so how can I define them inside the ops manager definition?

**Comment by antonlisovenko** [comment]
Hi @tareksalem 

I'd still like to clarify the task more

> when I create the om without defining the PVC the created containers takes a random persistent volume claim
Not sure I understand this. Let me try to explain the architecture a bit.

For each MongoDBOpsManager resource the Operator creates at least two StatefulSets: one for the application database and one for the Ops Manager application. Optionally the third StatefulSet can be created for Backup Daemon. 
The only `PersistentVolumeClaim` created is for the Application database in case if `persistent` is set to `true` (it's enabled by default). The other PVC is created for the Backup Daemon (for the HeadDB) but I guess it's not relevant for the given example.
There are some additional volumes/mounts for each pod which serve as internal mechanisms to pass some configuration/scripts to the pod but they don't relate to PVC.

If you want to configure the PVCs created for the Application database then you can set the `podSpec.persistence` configuration: https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-om-specification/#opsmgrkube.spec.applicationDatabase and this will change the parameters of the PVC created by the Operator.

**Comment by tareksalem** [comment]
@antonlisovenko 
here is a brief about what I want to achieve

I used the default template of ops manager to create MongoDB ops manager but when I apply it in Kubernetes, its applied but when checking the om status by running this command
```
kubectl get om -n mongodb
```
I get that the created om has reconciling status and not run ever, when I checked the created pods internally that related to this om I found that their status is pending and when I described them I found that the pod failed to initialize the pod with this message:

```
Warning FailedScheduling default-scheduler running "VolumeBinding" filter plugin for pod "ops-manager-db-0": pod has unbound immediate PersistentVolumeClaims
```
This happens because this internal pod that is related to the created om selects a persistentVolumeClaim randomly which is `ops-manager-db-0` with the name of the pod

My problem now:

I have a created PVC and I want to select this PVC name in mongodb ops manager YAML file to allow the internal pods to use this persistent volume claim to mount the data to it

**Comment by antonlisovenko** [comment]
thanks for the update @tareksalem 

I see the problem now. 
So the PVC template for the AppDB is created by the Operator in case if `persistent` is set to `true` or omitted as I've described above. It has an empty `storageClass`, some default `size` and empty `labelSelector`.
The Kubernetes cluster usually creates a dynamic PV based on this PVC values. In your case it failed to create a dynamic PV because:
- either it doesn't support the dynamic volumes provisioning
- or it cannot create a dynamic volume based on the default parameters for the PVC 

What I'd recommend to you is to play with a simplified example and create a pod with `busybox` and try to use the same PVC that is created by the Operator for the appdb and check if it gets mounted to the volume automatically and if not - why not.
Maybe you just need to specify special PVC configuration that will make things work

**Comment by tareksalem** [comment]
thanks for your response @antonlisovenko 

I already checked the dynamic PVC that is created and found it has some fails to mount the data to the pv

so please guide me how can I specify a special PVC configuration in the MongoDB ops manager definition

**Comment by tareksalem** [comment]
Hi @antonlisovenko 
can you please help me because this blocks me

**Comment by antonlisovenko** [comment]
@tareksalem 

My recommendation stays the same: first try playing with the PVC values using `spec.applicationDatabase.podSpec.persistence.single` (https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-om-specification/#opsmgrkube.spec.applicationDatabase). This will allow you to change the PVC Template configuration for the AppDB that the Operator will create. You don't need to provide custom PVC or mounts for your need. In fact, it's not possible to provide custom PVC **Templates** for AppDB or for the MongoDB resources - only for OpsManager pods.

The second action is to simplify the task and get some sample pod with some PVC and make sure dynamic volume provisioning works. If you find such PVC values then you can replicate them into `podSpec.persistence.single` and the volume will be provisioned for your appdb.

**Comment by tareksalem** [comment]
@antonlisovenko 

I actually trying to simplify the task, I followed the documentation you mentioned and added this definition for MongoDB ops manager
```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  replicas: 3
  version: 4.4.1
  adminCredentials: ops-manager-admin-secret
  configuration:
    mms.testUtil.enabled: "true"
  externalConnectivity:
    type: NodePort
  applicationDatabase:
    members: 3
    persistent: true
    podSpec:
      persistence:
      multiple:
        data:
          storage: 15G
          storageClass: mongodb-storage
        journal:
          storage: 15G
          storageClass: mongodb-storage
        logs:
          storage: 15G
          storageClass: mongodb-storage

```

the problem still exists my om status is reconciling and when checking its related pods I get this message

```
Warning FailedScheduling default-scheduler running "VolumeBinding" filter plugin for pod "ops-manager-db-0": pod has unbound immediate PersistentVolumeClaims
```

the only thing that I want is to enable the MongoDB ops manager to run successfully to go to the next step in setting MongoDB on Kubernetes 

thanks for your help
