### ISSUE TITLE
/opt/scripts/agent-launcher.sh: line 114: splittedAgentFlags[*]: unbound variable

### ISSUE THREAD

**Issue by brechtvalcke** [mongodb/mongodb-enterprise-kubernetes#144]
Hi, sadly my installation broke again..

Mongodb kubernetes operator 1.7 worked fine for about a month and than out of nowhere it broke `and` if I check the logs of the ops manager that is broken I get this error in there:
`/opt/scripts/agent-launcher.sh: line 114: splittedAgentFlags[*]: unbound variable`

I really don't understand! I removed the entire namespace and enterprise operator. Reinstalled everything again and I get the same error. It's really wierd! Why has this happened? And how do I resolve this?

**Comment by brechtvalcke** [comment]
This is a copy of a issue I misplaced here:
[link to community version ticket](https://github.com/mongodb/mongodb-kubernetes-operator/issues/211)

**Comment by brechtvalcke** [comment]
To answer questions of @chatton in the other thread:

Did this issue occur during an upgrade from 1.7.1 -> 1.8.0?

No I did not try to upgrade it just suddenly broke. Maybe because our kubernetes cluster terminates all pods once a day?

You mention that the Ops Manager deployment is broken, but the error you included looks like it came from one of the database pods.
Yes it is the ops manager application database that crashed. Sorry I didn't specify!

**Comment by chatton** [comment]
Hi @brechtvalcke 

It looks like one of the older images was accidentally retagged, the correct image should be back now, the image in question being `quay.io/mongodb/mongodb-enterprise-init-appdb:1.0.3`. 

Could you try and re-reploy Ops Manager and let me know if everything works as expected?

**Comment by james-callahan** [comment]
I still get this error with both latest and 1.0.5:
```
      image: 'quay.io/mongodb/mongodb-enterprise-init-appdb:1.0.5'
      imageID: docker-pullable://quay.io/mongodb/mongodb-enterprise-init-appdb@sha256:cec52d1c459675dc25920fad9d8a6add3f5b1726760693c7cc9e02385affb367
```

**Comment by lopezavila85** [comment]
Hi @chatton,

We are experiencing the same trouble while upgrading from K8s Operator 1.5.5 to 1.7.1 in an Openshift 3.11 environment.
Just these lines appears in the logs tab:

```
{"logType":"agent-launcher-script","contents":"Using Kubernetes CA file"}
--
  | {"logType":"agent-launcher-script","contents":"Created symlink: /data/journal -> /journal"}
  | {"logType":"agent-launcher-script","contents":"Automation Agent version: 10.2.15.5958-1"}
  | {"logType":"agent-launcher-script","contents":"Mongodb Agent is configured to run in \"headless\" mode using local config file"}
  | /opt/scripts/agent-launcher.sh: line 114: splittedAgentFlags[*]: unbound variable


```

We are using the quay.io/mongodb/mongodb-enterprise-init-appdb:1.0.3 image and the AppDB definition in the Ops Manager YAML is as follows:
```

  applicationDatabase:
    members: 3
    podSpec:
      persistence:
        single:
          storage: 16Gi
      podTemplate:
        spec:
          securityContext:            
            fsGroup: 1003630000
            runAsNonRoot: true
            runAsUser: 1000
          containers:
            - name: mongodb-enterprise-appdb
              resources:
                limits:
                  cpu: '2'
                  memory: 4Gi
                requests:
                  cpu: '1'
                  memory: 2Gi

```
