### ISSUE TITLE
Cannot create a MongoDB Replica running inside Istio Mesh

### ISSUE THREAD

**Issue by tobernguyen** [mongodb/mongodb-enterprise-kubernetes#145]
So this is my MongoDB CR:

```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: api-db
spec:
  members: 3
  version: 4.4.1-ent
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: ops-manager-credential
  
  podSpec:
    persistence:
      single:
        storage: 10Gi
        storageClass: ebs-sc
```

Three pods (of a statefulset) are spun up but none of them was able to connect to other pods. The logs just say connection timeout.

It is very to reproduce:
- Have Istio installed (I use 1.7.0)
- Create a namespace with Istio-injected enabled
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: api
    labels:
      istio-injection: enabled

```
- Then create a MongoDB ReplicaSet using the MongoDB CR above.

If I create the MongoDB ReplicaSet in a namespace that doesn't have Istio-injection enabled, it works perfectly.
