### ISSUE TITLE
MongoDB Operator 1.8 installed via OperatorHub in OpenShift 4.5.   Getting Atlas error.

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#149]
1. Created secret with atlas organization level API key.  White listed my OpenShift installation (by looking at the operator yaml errors).
2. Create config map that pointed to orgID
3. Successfully installed the MongoDB Operator 1.8 installed via OperatorHub in OpenShift 4.5
4. Tried to create instance.   
5. Instance failed and the yaml shows atlas error

```
status:
  lastTransition: '2020-10-23T03:49:21Z'
  message: >-
    Failed to prepare Ops Manager connection: Status: 404 (Not Found),
    ErrorCode: ATLAS_GROUP, Detail: Group 5f924d5b949bc34f0e466daf is an Atlas
    group; use the Atlas Public API at /api/atlas/v1.0 to access it.
  phase: Failed
  type: ''
  version: ''
```
<img width="1513" alt="Screen Shot 2020-10-22 at 8 49 19 PM" src="https://user-images.githubusercontent.com/749093/96954370-21428180-14a8-11eb-84a7-d36d5979b5e8.png">
<img width="1374" alt="Screen Shot 2020-10-22 at 8 49 31 PM" src="https://user-images.githubusercontent.com/749093/96954378-243d7200-14a8-11eb-82d1-ef4e5998f95d.png">

**Comment by alberttwong** [comment]
copy of my yaml to create my mongo instance
```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
  namespace: testing
spec:
  credentials: mongodbopsmanager
  members: 3
  opsManager:
    configMapRef:
      name: mongodb-test
  type: ReplicaSet
  version: 4.4.0-ent
  persistent: true
status:
  phase: Running
  type: ReplicaSet
```
