### ISSUE TITLE
MongoDB Operator 1.8.  Ops Manager yaml not enforcing required fields

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#151]
I noticed that adminCredentials and replicas variables are not being enforced as required fields or "*" next to them (I'm not quite sure how you make it known on the UI). See the screenshot.

```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: openshift-operators
spec:
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    podSpec:
      cpu: '1'
    persistent: true
    members: 3
  adminCredentials: ops-manager-admin-user-credentials
  configuration:
    mms.fromEmailAddr: admin@thecompany.com
  version: 4.4.1
  replicas: 1
```

<img width="1114" alt="Screen Shot 2020-10-22 at 11 23 31 PM" src="https://user-images.githubusercontent.com/749093/96963514-9ec4bc80-14bd-11eb-8c9b-590809eb4083.png">
