### ISSUE TITLE
OpenShift projects do not have access to Operator installed service accounts

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#157]
By default, the MongoDB operator is installed in "OpenShift-Operators" namespace and has access to all namespaces.   Also installed in that namespace are all the 4 key service accounts and their associated secrets.    The problem is when a user creates a new project/namespace and try to use the operator, they can interact with the operator but the service accounts are not available in their namespace.    We could recreate all the service accounts and it's written that way in the docs but that is not optimal.

My suggestion is to do rolebinding or add roles to all users.   Thoughts?

**Comment by alberttwong** [comment]
So right now the operator can only work if you install it for specific namespace like shown in screenshot "ecommerce".   It won't work if you pick all.
<img width="902" alt="Screen Shot 2020-10-23 at 3 41 23 PM" src="https://user-images.githubusercontent.com/749093/97059773-42f24600-1546-11eb-85de-8f6fa15d6ebb.png">

**Comment by alberttwong** [comment]
In the meantime, I've asked for more documentation to be written to have 1. install in all namespaces and 2. need to create service accounts for each namespace you want to use mongodb.

https://jira.mongodb.org/browse/DOCS-13947

**Comment by alberttwong** [comment]
I see that https://docs.mongodb.com/kubernetes-operator/master/tutorial/plan-k8s-op-considerations/#cluster-wide-scope can allow individual project to create the 4 needed service accounts.

**Comment by alberttwong** [comment]
sample

```
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  namespace: ecommerce
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-ops-manager
  namespace: ecommerce
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-enterprise-appdb
    namespace: ecommerce
```
