### ISSUE TITLE
MongoDB Operator 1.8 in OpenShift UI asking for required parameter where there should be none.

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#158]
<img width="660" alt="Screen Shot 2020-10-26 at 6 11 20 PM" src="https://user-images.githubusercontent.com/749093/97244768-c9ad5a00-17b6-11eb-994f-423bb8a70f6f.png">

If you just go through the UI and try to provision a cluster, it'll show that you need more parameter filled out even though you don't need it.

I usually have to switch to the YAML view and "create" it.   Here's a sample of what YAML I used.
```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: albert-wong-ocp2
  namespace: testing
spec:
  credentials: mongodbopsmanager
  members: 3
  cloudManager:
    configMapRef:
      name: mongodb-test
  type: ReplicaSet
  version: 4.4.0-ent
  persistent: true
status:
  phase: Running
  type: ReplicaSet
```
