### ISSUE TITLE
Minikube.  Cannot see MongoDB cluster deployed.

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#163]
After deploying the MongoDB replica.  It doesn't show.

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set4
  namespace: mongodb
spec:
  credentials: mongodb-opsmanager-creds
  members: 3
  opsManager:
    configMapRef:
      name: mongodb-cloudmanager-orgid
  type: ReplicaSet
  version: 4.4.0-ent
  persistent: false
status:
  phase: Running
  type: ReplicaSet
```
