### ISSUE TITLE
Docs are unclear how to apply clusterrole to watch * namespace

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#165]
The docs mention it but there are no instructions.

**Comment by alberttwong** [comment]
https://docs.mongodb.com/kubernetes-operator/master/tutorial/plan-k8s-op-considerations/#cluster-wide-scope

**Comment by alberttwong** [comment]
sample

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-enterprise-appdb
    namespace: ecommerce
```
