### ISSUE TITLE
Additional instructions when deploying MongoDB Operator in OpenShift watching * namespace.

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#168]
-- These instructions are used if you're using the MongoDB Operator configured to watch * namespace

-- create all the local project kube service accounts and secrets. You only need to do this once per project/namespace (example is using "ecommerce" project/namespace. JIRA ticket has been submitted to update docs (Oct 2020). I use the "import YAML" UI in OCP console
```
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  namespace: ecommerce
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-ops-manager
  namespace: ecommerce
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
# Source: mongodb-enterprise-operator/templates/database-roles.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-enterprise-appdb
  namespace: ecommerce
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-enterprise-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-enterprise-appdb
    namespace: ecommerce
    ```
