### ISSUE TITLE
documentation around replica set horizons is wrong

### ISSUE THREAD

**Issue by jfelten** [mongodb/mongodb-enterprise-kubernetes#171]
The public documentation around replica set horizons is wrong.

https://docs.mongodb.com/kubernetes-operator/v1.9/tutorial/deploy-replica-set/#deploy-replica-set

If I try to follow the doc example:

```
security:
    tls:
      enabled: true
  connectivity:
    replicaSetHorizons:
      - "example-website": "web1.example.com:30907"
      - "example-website": "web2.example.com:32350"
      - "example-website": "web3.example.com:31185"
```

This gives the error:
```
error validating data: ValidationError(MongoDB.spec): unknown field "connectivity" in com.mongodb.v1.MongoDB.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

Looking at the enterprise crd code it is not there, but it is there in the community crd: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_mongodb_crd.yaml. Can this either be ported or the documentation updated?
