### ISSUE TITLE
[RFE] Possiility to add limits to OpsManager

### ISSUE THREAD

**Issue by bandrade** [mongodb/mongodb-enterprise-kubernetes#175]
**What did you do to encounter the bug?**
I have an automation that ensures that MongoDB Operator can be successfully installed on Openshift, but our CI environment doesn't have so many resources and OpsManager requires 5G per pod. For applicationDatabase pods:

```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    podSpec:
      cpu: "200m"
      memory: "300M"
    persistent: false
    members: 3
  opsManager:
    podSpec:
      cpu: "200m"
      memory: "300M"
  adminCredentials: opsman-admin-credentials
  configuration:
    mms.fromEmailAddr: admin@thecompany.com
  version: 4.4.1
```
But ops-manager still have 5G by default 
kubectl get statefulset ops-manager -o yaml -n mongodb
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ops-manager-svc
      controller: mongodb-enterprise-operator
      pod-anti-affinity: ops-manager
  serviceName: ops-manager-svc
  template:
    metadata:
      annotations:
        connectionStringHash: KEWA7I7XYHNVMUW57MZTXPNGDS2GG6FWVUWTOYZTPTPYFE3D3ANQ
      creationTimestamp: null
      labels:
        app: ops-manager-svc
        controller: mongodb-enterprise-operator
        pod-anti-affinity: ops-manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  pod-anti-affinity: ops-manager
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/scripts/docker-entry-point.sh
        env:
        - name: OM_PROP_automation_versions_directory
          value: /mongodb-ops-manager/mongodb-releases/
        - name: OM_PROP_mms_centralUrl
          value: http://ops-manager-svc.mongodb.svc.cluster.local:8080
        - name: OM_PROP_mms_featureControls_enable
          value: "true"
        - name: OM_PROP_mms_fromEmailAddr
          value: admin@thecompany.com
        - name: OM_PROP_mongo_mongoUri
          valueFrom:
            secretKeyRef:
              key: connectionString
              name: ops-manager-db-connection-string
        - name: CUSTOM_JAVA_MMS_UI_OPTS
          value: -Xmx4291m -Xms4291m
        - name: CUSTOM_JAVA_DAEMON_OPTS
          value: -Xmx4291m -Xms4291m
        image: registry.connect.redhat.com/mongodb/mongodb-enterprise-ops-manager:4.4.1
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /mongodb-ops-manager/bin/mongodb-mms stop_mms
        name: mongodb-ops-manager
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /monitor/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 5G
```
**What did you expect?**
Suggest to have an option to adjust opsManager limits

**What happened instead?**
Looks like opsManager is not considering podSpec limts

**Screenshots**

**Operator Information**
 - Operator Version: v1.8.0
 - Base Images used (ubuntu or UBI)

**Ops Manager Information**
 - Ops Manager Version
 - Is Ops Manager managed by the Operator or not?
 - Is Ops Manager in Local Mode?

**Kubernetes Cluster Information**
 - Distribution: Openshift 4.7
 - Version: k8s 1.20
