### ISSUE TITLE
Sharded Cluster stuck in Reconciling state due to issues in backup

### ISSUE THREAD

**Issue by soulaw-mkii** [mongodb/mongodb-enterprise-kubernetes#181]
Hi,

I have deployed ops-manager v1.9.1 and now trying to deploy a sharded cluster named 'market-data-store'. Each pod of mongod/mongos/config servers are running good. But no matter I disabled/enabled the backup option (where the backup is really saved to S3 bucket). The MDB status stuck in 'Reconciling', saying "There should be a maximum of one backup config per project!". 

Is there anything I missed in the setup? Please let me know if any more material is required.

Here is the status of Ops-manager 
```console
NAME          REPLICAS   VERSION   STATE (OPSMANAGER)   STATE (APPDB)   STATE (BACKUP)   AGE    WARNINGS
ops-manager   2          4.4.6     Running              Running         Running          4d9h
```
```console
NAME                                              READY   STATUS    RESTARTS   AGE
pod/mongodb-enterprise-operator-8578494dc-lcfjh   1/1     Running   0          4d9h
pod/ops-manager-0                                 1/1     Running   0          4d9h
pod/ops-manager-1                                 1/1     Running   1          4d9h
pod/ops-manager-backup-daemon-0                   1/1     Running   0          4d7h
pod/ops-manager-db-0                              1/1     Running   0          4d8h
pod/ops-manager-db-1                              1/1     Running   0          4d8h
pod/ops-manager-db-2                              1/1     Running   0          4d8h
pod/ops-manager-oplog-store-0                     1/1     Running   0          4d8h
pod/ops-manager-oplog-store-1                     1/1     Running   0          4d8h
pod/ops-manager-oplog-store-2                     1/1     Running   0          4d7h

NAME                                           TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                          AGE
service/operator-webhook                       ClusterIP      10.245.144.167   <none>         443/TCP                          4d9h
service/ops-manager-backup-daemon-svc          ClusterIP      None             <none>         8443/TCP                         4d8h
service/ops-manager-db-svc                     ClusterIP      None             <none>         27017/TCP                        4d9h
service/ops-manager-oplog-store-svc            ClusterIP      None             <none>         27017/TCP                        4d8h
service/ops-manager-oplog-store-svc-external   NodePort       10.245.69.0      <none>         27017:32078/TCP                  4d8h
service/ops-manager-svc                        ClusterIP      None             <none>         8443/TCP                         4d9h
service/ops-manager-svc-ext                    LoadBalancer   10.245.249.104   192.168.2.92   8443:30100/TCP,25999:31447/TCP   4d9h

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mongodb-enterprise-operator   1/1     1            1           4d9h

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/mongodb-enterprise-operator-8578494dc   1         1         1       4d9h

NAME                                         READY   AGE
statefulset.apps/ops-manager                 2/2     4d9h
statefulset.apps/ops-manager-backup-daemon   1/1     4d8h
statefulset.apps/ops-manager-db              3/3     4d9h
statefulset.apps/ops-manager-oplog-store     3/3     4d8h
```

Here is my configuration about backup in ops-manager
```console
:
backup:
    enabled: true
    headDB:
      storage: 150Gi
      labelSelector:
        matchLabels:
          application: headdb
          env: production
      storageClass: hdd-r6  
    opLogStores:       
      - name: ops-manager-oplog-store
        mongodbResourceRef:
          name: ops-manager-oplog-store
        mongodbUserRef:
          name: ops-manager-oplog-store-admin
    s3Stores:
      - name: mongodb-snapshot-store
        # the name of the secret which contains aws credentials
        s3SecretRef:
          name: mongodb-snapshot-store-service-account-secret 
        s3BucketEndpoint: s3.ap-east-1.amazonaws.com
        s3BucketName: mongodb-snapshot-store
        pathStyleAccessEnabled: true
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: mongodb-backup-daemon
              resources:
                requests:
                  cpu: '50m'
                  memory: '2048Mi'
                limits:
                  cpu: '100m'
                  memory: '3072Mi'
```

Here is the exception from mongodb-enterprise-operator
```console
{
    "level": "error",
    "ts": 1611765487.3696861,
    "caller": "workflow/failed.go:67",
    "msg": "Failed to create/update (Ops Manager reconciliation phase): There should be a maximum of one backup config per project!",
    "ShardedCluster": "prd/market-data-store",
    "stacktrace": "github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/workflow.failedStatus.Log\n\t/go/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/workflow/failed.go:67\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatus\n\t/go/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:129\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).Reconcile\n\t/go/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:84\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"
}

```

**Ops Manager Information**
 - Ops Manager Version: 4.4.6
 - Is Ops Manager managed by the Operator or not? Yes
 - Is Ops Manager in Local Mode? No

**Kubernetes Cluster Information**
 - Distribution: Ubuntu 20.04
 - Version: v1.19.3
 - Image Registry location (quay, or an internal registry): quay

Regards,
Steve

**Comment by soulaw-mkii** [comment]
Enriched the exception log above

**Comment by soulaw-mkii** [comment]
In parallel, I deployed a replica-set under the same workspace. It 's running good.
```console
NAME                TYPE             STATE         VERSION     AGE
market-data-store   ShardedCluster   Reconciling   4.4.3-ent   12h
test-rs             ReplicaSet       Running       4.4.3-ent   6m54s
```

Here is manifest:
```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: test-rs
spec:
  type: ReplicaSet
  version: 4.4.3-ent
  featureCompatibilityVersion: "4.4"
  clusterDomain: stevetasks.io
  
  logLevel: ERROR
  members: 3
  persistent: true
  exposedExternally: true
  service: test-rs-svc

  backup:
    mode: enabled
  opsManager:
    configMapRef:
      name: test-rs-cm
  credentials: day-day-is-good-day-org-owner-api-secret
  # credentials: ops-manager-db-owner-api-secret

  security:
    tls:
      enabled: true
      ca: ops-manager-ca-cert 
    authentication:
      enabled: true
      modes: ["SCRAM"]

  # 'podTemplate' allows to set custom fields in PodTemplateSpec (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podtemplatespec-v1-core)
  # for the Database StatefulSet.
  podSpec: 
    persistence:
      single:
        labelSelector:
          matchLabels:              
            application: test-rs-prd
            env: production
        storage: 16Gi
        storageClass: hdd-r6
    podAntiAffinityTopologyKey: nodeId
    podTemplate:
      metadata:
        labels:
          # app: oplog-store
          env: production
      spec:
        securityContext:
          # Don't try the following as it fails but only fsGroup
          # runAsNonRoot: true
          # runAsUser: 2000 # however it does not affect ops-mgr
          # runAsGroup: 2000
          fsGroup: 2000 # POD level security       
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "200m"
                memory: "1024Mi"
              requests:
                cpu: "50m"
                memory: "200Mi"

```
