### ISSUE TITLE
Sharded Cluster fails to reconcile/deploy

### ISSUE THREAD

**Issue by peterjanes** [mongodb/mongodb-enterprise-kubernetes#182]
I've deployed operator 1.9.1 in an Azure AKS environment and am trying to deploy a simple `ShardedCluster`, but the operator logs say the agents are failing to register and the mdb is marked as having `Failed`.

Ops Manager shows all of the servers/agents that I'd expect. The cluster domain is `cluster.local` and the pod names appear to be correct (prefix-(config|mongos)-n); their hostnames can also be resolved from the ops manager pod and vice versa. (I've also tried with everything in a single namespace with the same results, and I also see the issue running through the steps at https://finisky.github.io/2020/12/26/mongodbomcreateshardedcluster.en/.)

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: sharded
spec:
  shardCount: 2
  mongosPerShardCount: 3
  mongosCount: 2
  configServerCount: 3
  version: 4.4.3-ent
  type: ShardedCluster

  persistent: true

  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: om-credentials
```

The operator and ops-manager pods are running:

```
$ kubectl -n mongodb-operator get om
NAME          REPLICAS   VERSION   STATE (OPSMANAGER)   STATE (APPDB)   STATE (BACKUP)   AGE     WARNINGS
ops-manager              4.4.3     Running              Running         Pending          3h15m   
```

```
$ kubectl -n mongodb-operator get pod
NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-enterprise-operator-6d79cbff47-qxmfl   1/1     Running   0          101m
ops-manager-0                                  1/1     Running   0          99m
ops-manager-backup-daemon-0                    1/1     Running   0          147m
ops-manager-db-0                               1/1     Running   0          148m
ops-manager-db-1                               1/1     Running   0          150m
ops-manager-db-2                               1/1     Running   0          151m
```

as are the sharded cluster pods:

```
$ kubectl -n mongodb get pod
NAME               READY   STATUS    RESTARTS   AGE
sharded-config-0   1/1     Running   0          34m
sharded-config-1   1/1     Running   0          35m
sharded-config-2   1/1     Running   0          36m
sharded-mongos-0   1/1     Running   0          33m
sharded-mongos-1   1/1     Running   0          33m
```

but the mdb is marked failed:

```
$ kubectl -n mongodb get mdb
NAME      TYPE             STATE    VERSION     AGE
sharded   ShardedCluster   Failed   4.4.3-ent   47m
```

Here's the error from the operator:

```
{
  "level":"error",
  "ts":1612378020.748433,
  "caller":"workflow/failed.go:67",
  "msg":"Failed to create/update (Ops Manager reconciliation phase): Some agents failed to register or the Operator is using the wrong host names for the pods. Make sure the 'spec.clusterDomain' is set if it's different from the default Kubernetes cluster name ('cluster.local')",
  "ShardedCluster":"mongodb/sharded",
  "stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/workflow.failedStatus.Log\n\t/go/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/workflow/failed.go:67\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatus\n\t/go/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:129\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).Reconcile\n\t/go/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:84\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

**Ops Manager Information**

    Ops Manager Version: 4.4.3
    Is Ops Manager managed by the Operator or not? Yes
    Is Ops Manager in Local Mode? No

**Kubernetes Cluster Information**

    Distribution: Azure AKS
    Version: v1.18.14
    Image Registry location (quay, or an internal registry): quay

**Comment by peterjanes** [comment]
Ops Manager was deployed by the operator per https://docs.mongodb.com/kubernetes-operator/master/tutorial/deploy-om-container/ (but with a version bump):

```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  version: 4.4.3
  adminCredentials: ops-manager-credentials
  externalConnectivity:
    type: LoadBalancer

  applicationDatabase:
    members: 3
```
