### ISSUE TITLE
Operator does not set status on CRs

### ISSUE THREAD

**Issue by robszumski** [mongodb/mongodb-enterprise-kubernetes#3]
When creating the supported CR objects, you need to provide data like a ConfigMap or Secret.

The Operator correctly detects and logs when these don't exist, but these statuses never make it back to the object itself. If you're the end-user that might not have access to the Operator logs, you never know this.

```
{"level":"error","ts":1536342801.123745,"caller":"operator/standalonekube.go:24","msg":"configmaps \"my-projectsdf\" not found" ...
```

For example, the etcd Operator writes a status similar to other built-in Kubernetes objects:

```
status:
  clientPort: 2379
  conditions:
    - lastTransitionTime: '2018-09-06T21:06:01Z'
      lastUpdateTime: '2018-09-06T21:06:01Z'
      reason: Cluster available
      status: 'True'
      type: Available
  currentVersion: 3.2.13
  members:
    ready:
      - example-4plxdcfp5q
      - example-bms2r5t28x
      - example-tbssq6h2bq
  phase: Running
  serviceName: example-client
  size: 3
```

In the Mongo case, setting a `status.phase = RequirementsNotMet` and a `status.reason = ConfigMap xxx not found` would help users debug these types of issues, as well as provide more insight into the functioning of the database cluster.
