### ISSUE TITLE
can't configure auto-generated service's name to match istio's requirements

### ISSUE THREAD

**Issue by hacktron95** [mongodb/mongodb-enterprise-kubernetes#39]
Hello,
i'm trying to run `mongodb-operator` on k8s with **istio**,
when the operator generate the headless service it uses a port name that doesn't follow istio requirements for pods and services that found [here](https://istio.io/docs/setup/additional-setup/requirements/)
based on that the port's name should follow `<protocol>-<suffix>` rule
but here is a snap from the default generated headless service by the operator
```
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  publishNotReadyAddresses: true
```
and whenever i edit the port name like this 

```
  ports:
  - name: tcp-mongodb
    port: 27017
    protocol: TCP
```
the operator set it back to it's default `mongodb`.
is it possible to make the port name configurable, to help addressing this kind of requirements?
thanks.
