### ISSUE TITLE
Storage syntax should be "Gi" not "G"

### ISSUE THREAD

**Issue by NickSchleicher** [mongodb/mongodb-enterprise-kubernetes#42]
The [mongodb docs](https://docs.mongodb.com/kubernetes-operator/v1.1/reference/k8s-operator-specification/) say `If this MongoDB Kubernetes resource requires 60 gigabytes of storage space, set this value to 60G.` However, [Kubernetes docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) for PVC have examples of only using `Gi` not `G`.

When I specified `500G` per mongodb operator docs, my PVC was created for only `466 gigabytes` instead of `500 gigabytes`
```
...
      persistence:
        single:
          storage: 500G
          storageClass: mongodb
```
```
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 500G
  storageClassName: mongodb
  volumeMode: Filesystem
  volumeName: pvc-c5febc6b-e514-11e9-bd1f-020dbfb1e118
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 466Gi
  phase: Bound
```

When I switched to `500Gi` it correctly gave my PVC `500 gigabytes`
```
...
      persistence:
        single:
          storage: 500Gi
          storageClass: mongodb
```
```
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 500Gi
  storageClassName: mongodb
  volumeMode: Filesystem
  volumeName: pvc-4e47c8cc-e558-11e9-bd1f-020dbfb1e118
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  phase: Bound
```
