### ISSUE TITLE
configuring backup daemon

### ISSUE THREAD

**Issue by sarkistlt** [mongodb/mongodb-enterprise-kubernetes#51]
I was trying to find any information about how to configure backup daemon, with current k8s setup, but wasn't able to find anything, anywhere. So is it possible to configure with self hosted ops manager? Or backup daemon is enterprise advance only?

**Comment by antonlisovenko** [comment]
Backup daemon will be configured by the Operator in the next release (1.4.0) which will be released very soon.

**Comment by sarkistlt** [comment]
@antonlisovenko it was fast) Thanks!

**Comment by sarkistlt** [comment]
when configuring ops. and s3 to use external db, it does configure, backup demean, but then when I'm trying to enable backup for deployment I'm getting `We're sorry, an unexpected error has occurred` error, so does backup works only with ops and s3 configured to use db deployed in the same cluster?

**Comment by antonlisovenko** [comment]
Can you show your OM and Mongodb resources configuration files please?

**Comment by sarkistlt** [comment]
Sure, here we go:

ops-manager

```yaml
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  replicas: 1
  version: 4.2.4
  adminCredentials: ops-manager-admin-secret
  configuration:
    mms.fromEmailAddr: "****"
    mms.replyToEmailAddr: "****"
    mms.adminEmailAddr: "****"
    mms.mail.transport: "smtp"
    mms.mail.hostname: "smtp.sendgrid.net"
    mms.mail.port: "25"
    mms.mail.username: "apikey"
    mms.mail.password: "****"
  backup:
    enabled: true
    headDB:
      storage: 50Gi
      storageClass: ssd-xfs

  applicationDatabase:
    members: 3
    version: 4.0.13
    logLevel: ERROR
    persistent: true
    podSpec:
      cpu: '2'
      memory: 10Gi
      cpuRequests: '1'
      memoryRequests: 2Gi
      persistence:
        single:
          storage: 10Gi
          storageClass: ssd-xfs
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: Exists
```

MongoDB
```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: staging-db
  namespace: mongodb
spec:
  type: ShardedCluster
  exposedExternally: false
  service: staging-db
  version: 4.0.13
  mongosCount: 2
  configServerCount: 3
  shardCount: 2
  mongodsPerShardCount: 3
  opsManager:
    configMapRef:
      name: staging-db
  credentials: ops-manager-global-user
  security:
    authentication:
      enabled: true
      modes: ["SCRAM"] # sha256
      ignoreUnknownUsers: true
  logLevel: WARN
  persistent: true
  mongosPodSpec:
    cpu: '2'
    memory: 8Gi
    cpuRequests: '1'
    memoryRequests: 4Gi
    persistence:
      single:
        storage: 10Gi
        storageClass: ssd-xfs
    podAntiAffinityTopologyKey: kubernetes.io/hostname
  configSrvPodSpec:
    cpu: '2'
    memory: 8Gi
    cpuRequests: '1'
    memoryRequests: 4Gi
    persistence:
      single:
        storage: 10Gi
        storageClass: ssd-xfs
    podAntiAffinityTopologyKey: kubernetes.io/hostname
  shardPodSpec:
    cpu: '2'
    memory: 8Gi
    cpuRequests: '1'
    memoryRequests: 4Gi
    persistence:
      single:
        storage: 50Gi
        storageClass: ssd-xfs
    podAntiAffinityTopologyKey: kubernetes.io/hostname
```
