### ISSUE TITLE
PodSpecs don't support tolerations

### ISSUE THREAD

**Issue by kuhsaft** [mongodb/mongodb-enterprise-kubernetes#55]
The podSpecs for MongoDBOpsManager and MongoDB resources do not support adding tolerations to the pod specification.

**Comment by BenElgar** [comment]
Hi @kuhsaft! You're right that this is not yet supported but we are working on adding it and it should be available relatively soon.

**Comment by BenElgar** [comment]
This is tracked internally as CLOUDP-31700.

**Comment by antonlisovenko** [comment]
Tolerations can be set using `podTemplate` field as of Operator 1.4.2

**Comment by kuhsaft** [comment]
Is there any documentation on this other than the changelog?

**Comment by antonlisovenko** [comment]
Documentation will be published soon.
So far you check out the samples: https://github.com/mongodb/mongodb-enterprise-kubernetes/tree/master/samples/mongodb/pod-template

**Comment by kuhsaft** [comment]
I don't think it works right with the sharded cluster.

I get this error from the operator pod:
```
{"level":"error","ts":1580930086.209951,"caller":"operator/common_controller.go:291","msg":"Failed to create/update (Kubernetes reconciliation phase): Failed to create Stateful Set for shard mongodb-1: StatefulSet.apps \"mongodb-1\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","ShardedCluster":"default/mongodb","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatusFailed\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:291\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*errorStatus).updateStatus\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/reconcileresult.go:109\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbShardedCluster).Reconcile\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbshardedcluster_controller.go:48\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/65240722bdbb866b86667de974b8eee5/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

The first config pods and shard 0 statefulset updates correctly with the toleration, but shard 1 fails.

**Comment by antonlisovenko** [comment]
does this happen on creation or update of an existing sharded cluster?
Can you show your yaml configuration please?

**Comment by kuhsaft** [comment]
It occurs on update.

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
spec:
  shardCount: 3
  mongodsPerShardCount: 1
  mongosCount: 3
  configServerCount: 3
  version: "4.2.3"
  opsManager:
    configMapRef:
      name: mongodb-project
  credentials: mongodb-operator-credentials
  type: ShardedCluster
  persistent: true
  configSrvPodSpec:
    podTemplate:
      spec:
        tolerations:
        - key: "dedicated"
          value: "database"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - database
    persistence:
      single:
        storage: 16Gi
        storageClass: topology-aware-default
  shardPodSpec:
    cpu: "2"
    memory: 8Gi
    podTemplate:
      spec:
        tolerations:
        - key: "dedicated"
          value: "database"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - database
    podAntiAffinityTopologyKey: failure-domain.beta.kubernetes.io/zone
    persistence:
      single:
        storage: 32Gi
        storageClass: topology-aware-default
  mongosPodSpec:
    podTemplate:
      spec:
        tolerations:
        - key: "dedicated"
          value: "database"
  security:
    tls:
      enabled: true
    authentication:
      enabled : true
      modes: ["SCRAM"]
  additionalMongodConfig:
    net:
      ssl:
        mode: preferSSL
```

If I remove the `podTemplate` section, then all the shards update correctly.
