### ISSUE TITLE
how to create Ops Manager Instance offline

### ISSUE THREAD

**Issue by wangchong666** [mongodb/mongodb-enterprise-kubernetes#57]
Afer  exec 
`kubectl apply -f samples/ops-manager/ops-manager.yaml`
I got error message in the operator: 1.4.1 

```
{"level":"error","ts":1577436550.191347,"caller":"operator/appdbbreplicaset_controller.go:355","msg":"Get https://opsmanager.mongodb.com/static/version_manifest/4.2.json: dial tcp: lookup opsmanager.mongodb.com on 10.96.0.10:53: server misbehaving","ReplicaSet (AppDB)":"mongodb/ops-manager-db","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileAppDbReplicaSet).updateStatusFailedAppDb\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/appdbbreplicaset_controller.go:355\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileAppDbReplicaSet).Reconcile\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/appdbbreplicaset_controller.go:76\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*OpsManagerReconciler).Reconcile\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbopsmanager_controller.go:80\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/93316f9174b5627b789e4b87ab0c874e/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
It seems cannot access `https://opsmanager.mongodb.com/static/version_manifest/4.2.json` because my cluster is offline.

 http_proxy not work yet
mongodb-enterprise.yaml
```
        - name: http_proxy
          value: http://myproxy:3128
        - name: no_proxy
          value: '10,1'
```

**Comment by matancarmeli7** [comment]
I'm having the same problem.. 
Any solutions?

**Comment by rodrigovalin** [comment]
Hello, you can achieve this by passing the HTTP proxy configuration via the `configuration` section of the Ops Manager definition in the yaml file.

```yaml
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  replicas: 3
  version: 4.2.4
  adminCredentials: ops-manager-admin-secret

  # the Ops Manager configuration. All the values must be of type string
  configuration:
    http.proxy.host: "http://myproxy"
    http.proxy.port: "3128"
    # http.proxy.username: "username"
    # http.proxy.password: "password"

  applicationDatabase:
    members: 3
    version: 4.2.0
    persistent: true
    podSpec:
      cpu: '0.25'
```

The relevant Ops Manager documentation is [here](https://docs.opsmanager.mongodb.com/current/tutorial/use-with-http-proxy/index.html).
