### ISSUE TITLE
Issue using TLS Enabled using self signed certificates 

### ISSUE THREAD

**Issue by CAIOFCP** [mongodb/mongodb-enterprise-kubernetes#72]
Hi there, I'm currently trying to deploy a MongoDB 3.6 in Openshift 4.3 using TLS and the self signed certificate generated by the operator itself as described here.

https://docs.mongodb.com/kubernetes-operator/master/tutorial/secure-tls/

However when I deploy the MongoDB resource to the agents from the replica sets does not start properly with the following message in the monitoring-agent.log:

`[2020/02/20 12:59:26.315] [metrics.status.collector-my-replica-set-2.my-replica-set-svc.mongodb.svc.cluster.local:27017.error] [components/collector.go:looper:278] Failure during status metrics collection. Will retry after 10s.
Failed to get connectionStatus. Err: server selection error: server selection timeout
current topology: Type: Single
Servers:
Addr: my-replica-set-2.my-replica-set-svc.mongodb.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: x509: certificate signed by unknown authority
        at monitoring-agent/components/dialing.go:442
        at monitoring-agent/components/dialing.go:200
        at monitoring-agent/components/dialing.go:306
        at monitoring-agent/components/dialing.go:323
        at louisaberger/procexec/concurrency.go:45
        at src/runtime/asm_amd64.s:1357`

Bellow you can find my Ops Manager and MongoDB resources definitions:

`---`

  ```
 apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  type: ReplicaSet
  members: 3
  version: 3.6.17
  opsManager:
    configMapRef:
      name: my-project
  credentials: ops-manager-admin-key
  security:
    tls:
      enabled: true
    authentication:
      enabled: true
      modes: ["SCRAM"]
  additionalMongodConfig:   
    net:
      ssl:
        mode: allowTLS          
        allowConnectionsWithoutCertificates: true
        allowInvalidCertificates: true
        clientCertificateMode:  OPTIONAL
        CAFilePath: /mongodb-automation/ca.pem
  persistent: true
  podSpec:
    persistence:
      single:        
        storageClass: mongodbsc
        storage: 1Gi
```
```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  replicas: 3
  version: 4.2.4
  adminCredentials: ops-manager-admin-secret
  configuration:    
  backup:
    enabled: false
  applicationDatabase:
    members: 3
    version: 4.2.0
    persistent: true
    podSpec:
      cpu: '0.25'
      persistence:
        single:        
          storageClass: mongodbopssc

```
