### ISSUE TITLE
TLS key mismatch Issue in ReplicaSet

### ISSUE THREAD

**Issue by kpiyush17** [mongodb/mongodb-enterprise-kubernetes#76]
I had created a 3 member replica set using Kubernetes CA to enable TLS.
Deployment config:
```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mdb-replica-set
spec:
  members: 3
  version: 4.2.3
  opsManager:
    configMapRef:
      name: mdb-replica-set-project
  credentials: mdb-om-credentials
  type: ReplicaSet
  logLevel: INFO
  security:
    tls:
      enabled: true
    authentication:
      enabled: true
      modes: ["X509"]
      internalCluster: "X509"

  additionalMongodConfig:
    net:
      ssl:
        mode: "requireSSL"

  persistent: true
```

Now, to enable external access, I added the following lines to the deployment:
```
connectivity:
    replicaSetHorizons:
      - "mdb-replica-set-horizon": "dev-mongodb-0:31264"
      - "mdb-replica-set-horizon": "dev-mongodb-1:30710"
      - "mdb-replica-set-horizon": "dev-mongodb-2:32640"
```

After re-deploying, I am getting ssl issue in one of the replica set pods:

```
{"logType":"automation-agent-verbose","contents":"Config Used:"}
{"logType":"automation-agent-verbose","contents":"# THIS FILE IS MAINTAINED BY http://ops-manager-svc.mongodb.svc.cluster.local:8080 . DO NOT MODIFY AS IT WILL BE OVERWRITTEN."}
{"logType":"automation-agent-verbose","contents":"# To make changes to your MongoDB deployment, please visit http://ops-manager-svc.mongodb.svc.cluster.local:8080 . Your Group ID is 5e64a8b3d0c4ec0072116c23 ."}
{"logType":"automation-agent-verbose","contents":"net:"}
{"logType":"automation-agent-verbose","contents":"  bindIp: 0.0.0.0"}
{"logType":"automation-agent-verbose","contents":"  port: 27017"}
{"logType":"automation-agent-verbose","contents":"  ssl:"}
{"logType":"automation-agent-verbose","contents":"    CAFile: /mongodb-automation/ca.pem"}
{"logType":"automation-agent-verbose","contents":"    PEMKeyFile: /mongodb-automation/server.pem"}
{"logType":"automation-agent-verbose","contents":"    mode: requireSSL"}
{"logType":"automation-agent-verbose","contents":"processManagement:"}
{"logType":"automation-agent-verbose","contents":"  fork: \"true\""}
{"logType":"automation-agent-verbose","contents":"replication:"}
{"logType":"automation-agent-verbose","contents":"  replSetName: mdb-replica-set"}
{"logType":"automation-agent-verbose","contents":"security:"}
{"logType":"automation-agent-verbose","contents":"  authorization: enabled"}
{"logType":"automation-agent-verbose","contents":"  keyFile: /var/lib/mongodb-mms-automation/keyfile"}
{"logType":"automation-agent-verbose","contents":"setParameter:"}
{"logType":"automation-agent-verbose","contents":"  authenticationMechanisms: MONGODB-X509"}
{"logType":"automation-agent-verbose","contents":"storage:"}
{"logType":"automation-agent-verbose","contents":"  dbPath: /data"}
{"logType":"automation-agent-verbose","contents":"  engine: wiredTiger"}
{"logType":"automation-agent-verbose","contents":"systemLog:"}
{"logType":"automation-agent-verbose","contents":"  destination: file"}
{"logType":"automation-agent-verbose","contents":"  path: /var/log/mongodb-mms-automation/mongodb.log"}
{"logType":"automation-agent-verbose","contents":"\t- Output (stdout/stderr): "}
{"logType":"automation-agent-verbose","contents":"2020-03-18T09:28:12.899+0000 W  CONTROL  [main] Option: net.ssl.CAFile is deprecated. Please use net.tls.CAFile instead."}
{"logType":"automation-agent-verbose","contents":"2020-03-18T09:28:12.900+0000 W  CONTROL  [main] Option: net.ssl.PEMKeyFile is deprecated. Please use net.tls.certificateKeyFile instead."}
{"logType":"automation-agent-verbose","contents":"about to fork child process, waiting until server is ready for connections."}
{"logType":"automation-agent-verbose","contents":"forked process: 8095"}
{"logType":"automation-agent-verbose","contents":"ERROR: child process failed, exited with error number 1"}
{"logType":"automation-agent-verbose","contents":"To see additional information in this output, start without the \"--fork\" option."}
{"logType":"automation-agent-verbose","contents":""}
{"logType":"automation-agent-verbose","contents":"\t- Mongo Logs: "}
{"logType":"automation-agent-verbose","contents":"2020-03-18T09:28:12.990+0000 E  NETWORK  [main] cannot use PEM key file: /mongodb-automation/server.pem error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch"}
{"logType":"automation-agent-verbose","contents":"2020-03-18T09:28:12.990+0000 F  CONTROL  [main] Failed global initialization: InvalidSSLConfiguration: Can not set up PEM key file."}
{"logType":"automation-agent-verbose","contents":" : exit status 1"}
```
