### ISSUE TITLE
configmap to old resource version

### ISSUE THREAD

**Issue by brechtvalcke** [mongodb/mongodb-enterprise-kubernetes#80]
I've followed all the install steps in the docs. However, when I try to create an ops manager it gives a timeout. I checked the logs in the mongodb enterprise operator and I seem to get this error every time I try to create the ops manager that gives a timeout.:
`sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:204: watch of *v1.ConfigMap ended with: too old resource version: 7893407 (7895625)`

I followed these install steps:

```
kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-enterprise-kubernetes/master/crds.yaml
kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-enterprise-kubernetes/master/mongodb-enterprise.yaml
```
Of course the stars are my login information that I replaced to post them here.
`kubectl create secret generic ops-manager-admin-secret --from-literal=Username="****"  --from-literal=Password="****"  --from-literal=FirstName="****"  --from-literal=LastName="***" -n mongodb`

And finally this is how my ops manager resource looks like:
```
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  version: 4.2.4
  adminCredentials: ops-manager-admin-secret
  applicationDatabase:
    members: 3
    version: 4.2.2
```

I have installed it this way before on an older cluster and there it is already working. However I can't get it running on this cluster. Do note that this cluster is a private cluster in GKE but has access to the internet via cloud NAT.

Any ideas what is wrong?
