### ISSUE TITLE
[Ops Manager] Can't login into my admin user - AKS

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#81]
I created a secret for admin credentials:
`kubectl create secret generic ops-manager-admin-secret 
  --from-literal=Username="****" 
  --from-literal=Password="****" 
  --from-literal=FirstName="****" 
  --from-literal=LastName="****"`
And then used this yaml to deploy my om:
```yaml
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  # the number of Ops Manager instances to run. Set to value bigger
  # than 1 to get high availability and upgrades without downtime
  replicas: 1
  podSpec:
    memory: 2G
  externalConnectivity:
    type: LoadBalancer
    port: 443

  # the version of Ops Manager distro to use
  version: 4.2.4
  backup:
    podSpec:
      memory: 1G
    enabled: true
    opLogStores:
      - name: oplog-db
        mongodbResourceRef:
          name: ops-manager-oplog-db # Should match metadata.name
                                    # in the MongoDB database resource
                                    # for the oplog store
  # specify the custom cluster domain of the Kubernetes cluster if it's different from the default one ('cluster.local').
  # This affects the urls generated by the Operator.
  # This field is also used for Application Database url
  # clusterDomain: mycompany.net

  # the name of the secret containing admin user credentials.
  # Either remove the secret or change the password using Ops Manager UI after the Ops Manager
  # resource is created!
  adminCredentials: ops-manager-admin-secret
  
  # the Ops Manager configuration. All the values must be of type string
  configuration:
    mms.fromEmailAddr: "mongotest@noreply.com"
    # set this property to allow Ops Manager to manage deployments outside of
    # Kubernetes cluster
    mms.centralUrl: http://ac783a3d4b414-693915327.us-east-2.elb.amazonaws.com:8080

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    version: 4.2.0
    persistent: true
    podSpec:
      cpu: '0.25'
```

But still, when i get to the login page, I can't login with the admin password I've set.
