### ISSUE TITLE
How to create OPS Manager?

### ISSUE THREAD

**Issue by bergkvist** [mongodb/mongodb-enterprise-kubernetes#90]
What I've done so far:
```sh
kubectl create namespace mongodb
kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-enterprise-kubernetes/master/crds.yaml
kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-enterprise-kubernetes/master/mongodb-enterprise.yaml
kubectl create secret generic ops-manager-admin-secret  --from-literal=Username="jane.doe@example.com" --from-literal=Password="Passw0rd."  --from-literal=FirstName="Jane" --from-literal=LastName="Doe" -n mongodb
```

I modified the `ops-manager-external.yaml`-file:
```yaml
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-external
spec:
  replicas: 1
  version: 4.2.12
  adminCredentials: ops-manager-admin-secret
  # optional. Disabled by default. Creates an additional service to make Ops Manager reachable from
  # outside of the Kubernetes cluster.
  externalConnectivity:
    # LoadBalancer|NodePort
    type: NodePort
    # optional. Corresponds to NodePort port
    port: 30100
    # optional
    #loadBalancerIP: 123.456.789
    # optional
    #externalTrafficPolicy: Local
    # optional
    # For more information, read https://kubernetes.io/docs/concepts/services-networking/service/ about
    # what kind of annotations you can use, based on your Cloud provider.
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
  applicationDatabase:
    members: 3
    version: 4.2.6-ent
    persistent: true
```

And applied it:
```sh
kubectl apply -f ./ops-manager-external.yaml
```

And waited 20 minutes:
```sh
$ kubectl get mongodbopsmanager.mongodb.com/ops-manager-external -n default
NAME                   REPLICAS   VERSION   STATE (OPSMANAGER)   STATE (APPDB)   STATE (BACKUP)   AGE   WARNINGS
ops-manager-external   1          4.2.12                                                          21m   
```

Nothing seems to actually happen here. What am I doing wrong?
