### ISSUE TITLE
Unable to deploy MongoDBOpsManager sample in Openshift

### ISSUE THREAD

**Issue by mrethers** [mongodb/mongodb-enterprise-kubernetes#96]
Openshift 4.2 with MongoDB Operator 1.4.5

When trying to deploy a simple ops manager CR in my cluster, the pods cannot be created because of the Security Context Constraints on the pod and container spec: fsGroup: Invalid Value 2000 and runAsUser, same story. This is because the ops manager DB pods are configured to run with the mongodb-enterprise-appdb service account, which gets the restricted scc by default. The ops manager pods are running with the default service account which also gets the restricted scc by default. 

Since there is no way to customize the securityContext flags in the pod & container spec, the only way I got it to work was by adding the privileged scc to both service accounts but that's not a secured approach.

I can see the MANAGED_SECURITY_CONTEXT flag set to false in the operator but I'm not sure this is correct. Since I installed the operator from the Openshift web console, I didn't get a chance to modify that flag.

MongoDBOpsManager:

```
spec:
  adminCredentials: opsman-admin-credentials
  applicationDatabase:
    members: 3
    passwordSecretKeyRef:
      key: password
      name: opsman-db-password
    persistent: false
    podSpec:
      cpu: '0.25'
    version: 4.2.2-ent
  configuration:
    mms.fromEmailAddr: admin@thecompany.com
  externalConnectivity:
    type: LoadBalancer
  replicas: 1
  version: 4.2.8
```
